apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/edu/.minikube/ca.crt
    server: https://192.168.99.101:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    namespace: default
    user: minikube
  name: minikube
- context:
    cluster: minikube
    namespace: lfs158
    user: student
  name: student-context
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/edu/.minikube/profiles/minikube/client.crt
    client-key: /home/edu/.minikube/profiles/minikube/client.key
- name: student
  user:
    client-certificate: /home/edu/rbac/student.crt
    client-key: /home/edu/rbac/student.key
